package db;

import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

public class DatabaseInitializer {

    public static void initDatabase() {
        String createTableSql = """
            CREATE TABLE IF NOT EXISTS historial_lentes (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                nombre_lente VARCHAR(100),
                fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                curva_base DOUBLE,
                material VARCHAR(100),
                indice DOUBLE,
                esferico DOUBLE,
                cilindro DOUBLE,
                curva1 DOUBLE,
                curva2 DOUBLE,
                torsion DOUBLE
            )
            """;

        try (
                Connection conn = DatabaseConfig.getConnection();
                Statement stmt = conn.createStatement()
        ) {
            stmt.execute(createTableSql);

            try {
                stmt.execute("ALTER TABLE historial_lentes ADD COLUMN nombre_lente VARCHAR(100)");
            } catch (SQLException ignored) {
            }

        } catch (SQLException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog((Component) null,
                    "No se pudo inicializar la base de datos.");
        }
    }
}